networks:
  custom-network:
    driver: bridge

services:
  openresty:
    image: hieupth/openresty
    container_name: openresty
    restart: always
    # Security: Run as non-root user
    user: 1001:1001
    # Security: Read-only root filesystem
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    # Security: Drop all capabilities
    cap_drop:
      - ALL
    # Security: No new privileges
    security_opt:
      - no-new-privileges:true
    networks:
      - custom-network
    ports:
      - 80:8080
      - 443:8443
    env_file:
      - deploy.env
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ~/ssl:/ssl:ro
      - ./logs/nginx:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
